autokl:
  symbol: autokl
  find_unused_parameters: false

autokl_v1:
  super_cfg: autokl
  type: autoencoderkl
  args:
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 2, 4, 4]
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig: null
  pth: pretrained/kl-f8.pth

autokl_v2:
  super_cfg: autokl_v1
  pth: pretrained/pfd/vae/sd-v2-0-base-autokl.pth
