pfd_base:
  symbol: pfd
  find_unused_parameters: true
  type: pfd
  args:
    beta_linear_start: 0.00085
    beta_linear_end: 0.012
    timesteps: 1000
    use_ema: false

pfd_seecoder:
  super_cfg: pfd_base
  args:
    vae_cfg_list:
      - [image, MODEL(autokl_v2)]
    ctx_cfg_list:
      - [image, MODEL(seecoder)]
    diffuser_cfg_list:
      - [image, MODEL(openai_unet_2d_v1)]
    latent_scale_factor: 
      image: 0.18215

pdf_seecoder_pa:
  super_cfg: pfd_seecoder
  args:
    ctx_cfg_list:
      - [image, MODEL(seecoder_pa)]

pfd_seecoder_with_controlnet:
  super_cfg: pfd_seecoder
  type: pfd_with_control
  args:
    ctl_cfg: MODEL(controlnet)
